# 🗂️ Kubernetes Manifests für Big Data Stack
# ==========================================

apiVersion: v1
kind: Namespace
metadata:
  name: big-data
---
# MinIO Data Lake Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: big-data
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - :9090
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin123
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9090
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: big-data
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    nodePort: 30900
  - name: console
    port: 9090
    targetPort: 9090
    nodePort: 30901
  type: NodePort
---
# MinIO Setup Job - Erstellt Buckets und Beispieldaten
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup-job
  namespace: big-data
spec:
  template:
    spec:
      containers:
      - name: minio-setup
        image: minio/mc:latest
        command: ['sh', '-c']
        args:
        - |
          echo "Configuring MinIO client..."
          mc alias set myminio http://minio:9000 minioadmin minioadmin123
          
          echo "Creating buckets..."
          mc mb myminio/raw-data || echo "Bucket raw-data already exists"
          mc mb myminio/processed-data || echo "Bucket processed-data already exists"
          
          echo "Creating and uploading sample CSV data..."
          cat > /tmp/test-data.csv << 'CSVEND'
          food_item,weight_grams,calories,protein_g,carbs_g,fat_g
          apple,100,52,0.3,14,0.2
          banana,100,89,1.1,23,0.3
          chicken_breast,100,165,31,0,3.6
          rice_white,100,130,2.7,28,0.3
          broccoli,100,25,3,5,0.3
          pasta,100,131,5,25,1.1
          salmon,100,208,20,0,12
          beef_ground,100,250,26,0,15
          potato,100,77,2,17,0.1
          spinach,100,23,2.9,3.6,0.4
          CSVEND
          mc cp /tmp/test-data.csv myminio/raw-data/
          
          echo "Creating and uploading processed data..."
          cat > /tmp/test-results.json << 'JSONEND'
          {
            "analysis_date": "2025-01-07T10:05:30Z",
            "total_foods": 10,
            "avg_calories": 145.0,
            "high_protein_foods": ["chicken_breast", "salmon", "beef_ground"],
            "low_calorie_foods": ["spinach", "broccoli", "apple"],
            "data_source": "raw-data/test-data.csv"
          }
          JSONEND
          mc cp /tmp/test-results.json myminio/processed-data/
          
          echo "Demo buckets and data created successfully!"
          echo "Listing all buckets:"
          mc ls myminio/
          echo "Files in raw-data:"
          mc ls myminio/raw-data/
          echo "Files in processed-data:"
          mc ls myminio/processed-data/
      restartPolicy: Never
  backoffLimit: 3
