apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-GENERATOR_ID
  namespace: kafka
  labels:
    app: load-test
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: load-producer
        image: confluentinc/cp-kafka:7.4.0
        command:
        - /bin/bash
        - -c
        - |
          echo "High-intensity load generator GENERATOR_ID starting..."
          echo "Target: 2500 messages in 5 minutes"
          
          for j in {1..500}; do
              for k in {1..5}; do
                  TEMP=$((RANDOM % 80 - 20))
                  HUMIDITY=$((RANDOM % 100))
                  SENSOR_ID="sensor_$((RANDOM % 100))"
                  
                  echo "{\"timestamp\":\"$(date +"%Y-%m-%d %H:%M:%S")\",\"sensor_id\":\"$SENSOR_ID\",\"temperature\":$TEMP,\"humidity\":$HUMIDITY}" | kafka-console-producer --bootstrap-server kafka-headless:9092 --topic sensor-data &
              done
              
              for k in {1..3}; do
                  USER_ID=$((RANDOM % 2000))
                  ACTION="action_$((RANDOM % 10))"
                  PAGE_ID=$((RANDOM % 200))
                  
                  echo "{\"timestamp\":\"$(date +"%Y-%m-%d %H:%M:%S")\",\"user_id\":$USER_ID,\"action\":\"$ACTION\",\"page_id\":$PAGE_ID}" | kafka-console-producer --bootstrap-server kafka-headless:9092 --topic user-events &
              done
              
              sleep 0.05
              
              if [ $((j % 100)) -eq 0 ]; then
                  echo "Generator GENERATOR_ID: Burst $j completed"
              fi
          done
          
          echo "Load generator GENERATOR_ID completed: 2500 messages sent"